/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{js,ts,tsx}',
    './components/**/*.{js,ts,tsx}',
    './screens/**/*.{js,ts,tsx}',
    './navigation/**/*.{js,ts,tsx}',
  ],

  darkMode: 'class',
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#ffffff',
        foreground: '#0f172a',
        card: '#ffffff',
        'card-foreground': '#0f172a',
        popover: '#ffffff',
        'popover-foreground': '#0f172a',
        primary: '#3182f6',
        'primary-foreground': '#ffffff',
        secondary: '#f3f4f6',
        'secondary-foreground': '#0f172a',
        muted: '#f5f5f5',
        'muted-foreground': '#64748b',
        accent: '#f3f4f6',
        'accent-foreground': '#0f172a',
        destructive: '#ef4444',
        border: '#e5e7eb',
        input: '#e5e7eb',
        ring: '#93c5fd',
        'chart-1': '#2563eb',
        'chart-2': '#06b6d4',
        'chart-3': '#7c3aed',
        'chart-4': '#22c55e',
        'chart-5': '#f59e0b',
        sidebar: '#f8fafc',
        'sidebar-foreground': '#0f172a',
        'sidebar-primary': '#3182f6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#eef2f7',
        'sidebar-accent-foreground': '#0f172a',
        'sidebar-border': '#e5e7eb',
        'sidebar-ring': '#93c5fd',
      },
      borderRadius: {
        app: '10px',
      },
    },
  },
  plugins: [],
};
